apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: joycrew-cluster
  region: ap-northeast-2
  version: "1.29"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: joycrew-service-account
        namespace: default
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

vpc:
  id: "vpc-067968d8c7f0de694" # 기존 VPC ID 사용
  subnets:
    private:
      ap-northeast-2b: { id: "subnet-0b1c4ed704fe8809c" }
      ap-northeast-2d: { id: "subnet-00394d1c845cc1187" }
    public:
      ap-northeast-2a: { id: "subnet-03e9e38db1457d819" }
      ap-northeast-2c: { id: "subnet-0283caa043409b846" }

managedNodeGroups:
  - name: app-workers
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    ssh:
      allow: true
      publicKeyName: joycrew-deploy-key
    labels:
      role: application
      environment: production
    volumeSize: 20
    volumeType: gp3

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]